### ISSUE TITLE
Android throws an JS error: Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by edgardluz** [mishraas/jQuery-SSN-Field-Masking#1]
I can't really replicate it using android but I receive alerts from JS errors and Android throws the undefined variable for length. I've tried a bunch of checks on the maskssn.js so I'm thinking the error is in your version of the jquery.maskedinput.min.js though I can't figure it out where.

**Comment by mishraas** [comment]
Could you please share the logs(i.e. error with the loc number will do). If you have a sample that you have built which is accessible, it would be great.

Please use source version of the file while fetching logs.
Happy to help!

**Comment by MSustrick** [comment]
Hi, I was working with the maskedinput control and had the same issue. I copied the section for android events from the digital bush control, and was able to get to work on Android using BrowserStack for later versions. It appears there is still an issue with the older Android versions...

```
            function androidInputEvent() {
                    var curVal = input.val(), pos = input.caret();
                    if (oldVal && oldVal.length && oldVal.length > curVal.length) {
                        for (checkVal(!0) ; pos.begin > 0 && !tests[pos.begin - 1];) pos.begin--;
                        if (0 === pos.begin) for (; pos.begin < firstNonMaskPos && !tests[pos.begin];) pos.begin++;
                        input.caret(pos.begin, pos.begin);
                    } else {
                        for (checkVal(!0) ; pos.begin < len && !tests[pos.begin];) pos.begin++;
                        input.caret(pos.begin, pos.begin);
                    }
                    tryFireCompleted();
                }
                //function androidInputEvent() {
                //    var curVal = input.val(), pos = input.caret();
                //    if (curVal.length < oldVal.length) {
                //        for (checkVal(!0) ; pos.begin > 0 && !tests[pos.begin - 1];) pos.begin--;
                //        if (0 === pos.begin) for (; pos.begin < firstNonMaskPos && !tests[pos.begin];) pos.begin++;
                //        input.caret(pos.begin, pos.begin);
                //    } else {
                //        for (checkVal(!0) ; pos.begin < len && !tests[pos.begin];) pos.begin++;
                //        input.caret(pos.begin, pos.begin);
                //    }
                //    tryFireCompleted();
                //}
```

**Comment by MSustrick** [comment]
I tried that on Browser stack but when using softkeys it didn't work. I ended up putting out three text boxes that were typed as password. I had to code around it to restrict for numbers. I had to test for Android, and add an onchange event... and remove any non numeric characters....  so.. i had keydown event for regular users and change event for Android users
 $("input[id*='SSN']").on('change', function () {
        var ssnVal = $(this).val();
        var newVal = ssnVal.replace(/[^0-9]/g, '');
        console.log(newVal);
        $(this).val(newVal);
     });

**Comment by mishraas** [comment]
@MSustrick : Thanks for sharing your inputs. Do you have any specifics about the android version below which this issue is encountered. If you have any sample use case preferably a demo/fiddle somewhere, we can definitely try to fix it in the library and can try to avoid including another input field in solution as mentioned in your comment.

**Comment by reetaprajapatigate6** [comment]
@mishraas , keypad not working with masking in Android device in chrome browser. Can you please help me how can I resolve this issue 

![masking_issue](https://cloud.githubusercontent.com/assets/8192084/24904939/d1d0c2be-1ecf-11e7-86b0-2a4af7231a52.png)

**Comment by mishraas** [comment]
@reetaprajapatigate6 : Added fix for it. Please check against latest revision.
I am opening a separate issue for caret positioning though which exists in the core lib itself. Will fix that up soon.

**Comment by reetaprajapatigate6** [comment]
Hi,

Thank you so much for your quick response Ashutosh.
Now we are able to enter value in masked input field using android device
with chrome, but we have found another issue regarding the cursor now.
Cursor is not working properly, it stucks to wrong position after dash ( -)
as the user can type continuously e.g. I am tying 123, then cursor is stuck
at position of '1' and I am able to type in 2 & 3. Another problem we are
having is that we are unable to edit value for android device chrome, we
have checked it S5,S6,S7 which is the latest version of Samsung android
device

Can you please look into this and try to fix asap, we would like to use
this plugin and not look for another option just because of this small
margin of issue. Thank you very much Ashutosh.

**Comment by mishraas** [comment]
@reetaprajapatigate6 : Yes, I noticed the issue regarding cursor position on the same environment and thus created a separate issue for it. 
Could you please elaborate the edit value issue which you have pointed out. 

Thanks for your feedback though, I would see to it.
