### ISSUE TITLE
Hi. Thanks for your great plugin. Problems with unmask()

### ISSUE THREAD

**Issue by lemusi** [mishraas/jQuery-SSN-Field-Masking#6]
Hi, I am interested in testing the plugin, but I keep having problems loading the unmask() function.

Can you please tell me which external jQuery library I have to load in order for it to work? I have installed jQuery 1.12.4, so I don't understand why it's not detecting it.  Or maybe is a bug or something??  I have tried to load your js files in many ways and I still get the error.

This is the error I get:
TypeError: jQuery(...).unmask(...).maskSSN is not a function

I would appreciate your help a lot!

I am enqueuing files in wordpress like this:
`function my_theme_scripts() {
    wp_enqueue_script( 'maskssn', get_template_directory_uri() . '/js/jquery.js', array( 'jquery' ), '1.0.0', true );
	wp_enqueue_script( 'maskssn', get_template_directory_uri() . '/js/jquery.maskedinput.min.js', array( 'jquery' ), '1.0.0', true );
	wp_enqueue_script( 'maskssn', get_template_directory_uri() . '/js/jquery.maskssn.js', array( 'jquery' ), '1.0.0', true );
}
add_action( 'wp_enqueue_scripts', 'my_theme_scripts' ); `
 
And adding your code per page script:
`
jQuery(document).ready(function(){jQuery('.social').unmask().maskSSN('999-99-9999', {maskedChar:'X', maskedCharsLength:5});
			});`

**Comment by mishraas** [comment]
Hi,

The plugin uses jQuery v1.7.2 as of date. I have not tested it against newer versions yet.
The source code has the jquery library included.

For using the plugin I would suggest looking at the Demo page added at the root of the source code.

The issue may be due to multiple versions of jquery in your page, jQuery 1.12.4 and 1.7.2 loaded from plugin resource set.
